language: php


php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'


before_install:
  - composer install
  - if [[ $TRAVIS_PHP_VERSION == "5.6" ]]; then composer require satooshi/php-coveralls:dev-master -n ; fi

script:
  - vendor/bin/phpunit --debug


after_script:
  - if [[ $TRAVIS_PHP_VERSION == "5.6" ]]; then vendor/bin/coveralls -v ; fi
