sudo: required

language: php

services:
  - docker

before_install:
  - docker run --rm -v "$PWD":/var/src/ serkin/php7 composer install
  - docker run --rm -v "$PWD":/var/src/ serkin/php7 composer require satooshi/php-coveralls:dev-master -n

script:
  - docker run --rm -v "$PWD":/var/src/ serkin/php7 vendor/bin/phpunit --debug


after_script:
  - docker run --rm -v "$PWD":/var/src/ serkin/php7 php vendor/bin/coveralls -v
